# Generated by Django 5.0.4 on 2024-07-22 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assassin',
            old_name='secondary_weapon_type',
            new_name='assassination_technique',
        ),
        migrations.RenameField(
            model_name='shadowbladeassassin',
            old_name='shadow_walk_ability',
            new_name='shadowstep_ability',
        ),
        migrations.RenameField(
            model_name='timemage',
            old_name='time_manipulation_ability',
            new_name='temporal_shift_ability',
        ),
        migrations.RenameField(
            model_name='viperassassin',
            old_name='stealth_ability',
            new_name='venomous_bite_ability',
        ),
    ]
