# Generated by Django 5.0.4 on 2024-07-03 19:15

from django.db import migrations
from django.utils import timezone

def update_delivery_and_warranty(apps, schema_editor):
    order = apps.get_model('main_app', 'Order')

    for order in order.objects.all():
        if order.status == 'Pending':
            order.delivery = order.order_date + timezone.timedelta(days=3)
            order.save()
        elif order.status == 'Completed':
            order.warranty = "24 months"
            order.save()
        elif order.status == 'Cancelled':
            order.delete()


def revert_update_delivery_and_warranty(apps, schema_editor):
    order = apps.get_model('main_app', 'Order')

    for order in order.objects.all():
        if order.status == 'Pending':
            order.delivery = None
        elif order.status == 'Completed':
            order.warranty = order._meta.get_field('warranty').default

        order.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_order'),
    ]

    operations = [
        migrations.RunPython(update_delivery_and_warranty, revert_update_delivery_and_warranty),
    ]
