# Generated by Django 5.0.4 on 2024-07-03 19:32

from django.db import migrations


def update_rarity(apps, schema_editor):
    item_model = apps.get_model('main_app', 'Item')

    items = item_model.objects.all()

    for item in items:
        if item.price <= 10:
            item.rarity = "Rare"
        elif item.price <= 20:
            item.rarity = "Very Rare"
        elif item.price <= 30:
            item.rarity = "Extremely Rare"
        else:
            item_model.rarity = "Mega Rare"

    item_model.objects.bulk_update(items, ['rarity'])


def revert_rarity(apps, schema_editor):
    item_model = apps.get_model('main_app', 'Item')

    items = item_model.objects.all()

    for item in items:
        item.rarity = "No rarity"

    item_model.objects.bulk_update(items, ['rarity'])



class Migration(migrations.Migration):
    dependencies = [
        ('main_app', '0015_item'),
    ]

    operations = [
        migrations.RunPython(update_rarity, revert_rarity)
    ]
