# Generated by Django 5.0.4 on 2024-08-03 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_astronaut_name_alter_astronaut_spacewalks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='spacecraft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='main_app.spacecraft'),
        ),
    ]
