# Generated by Django 5.0.4 on 2024-08-03 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_mission_spacecraft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='commander',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commander_missions', to='main_app.astronaut'),
        ),
    ]
